dist: xenial
sudo: true

language: python
python:
  - 3.6
  - 3.7

before_install:
  - travis_retry python -m pip install --upgrade pip setuptools wheel

install:
  - python -m pip install ".[test]"

before_script:
  - travis_retry python -m pip install pytest-cov coverage codecov

script:
  - py.test -vs --cov niflow_manager --cov-report xml:cov.xml --doctest-modules niflow_manager

after_script:
  - codecov --file cov.xml --flags unittests -e TRAVIS_JOB_NUMBER
